<fieldset>
	<legend>CRIPTOGRAFIA EM PHP</legend>
	<form method = "POST">
	<label for = "inputTexto">Digite aqui o texto que deseja criptografar ou descriptografar</label>
	<br>
	<textarea id = "inputTexto" name = "inputTexto"></textarea>
	<br>
	<label for = "inputChave1">Chave para quebrar a criptografia</label>
	<br>
	<input type = "text" name = "inputChave1" id = "inputChave1">
	<br>
	<label for = "inputChave2">Chave 2 para quebrar a criptografia</label>
	<br>
	<input type = "text" name = "inputChave2" id = "inputChave2">
	<br>
	<select name = "selectEscolha">
		<option value = "criptografar">CRIPTOGRAFAR</option>
		<option value = "descriptografar">DESCRIPTOGRAFAR</option>
	</select>
	<br>
	<button value = "decriptografar">CONVERTER</button>
	</form>
</fieldset>
<!--
esse arquivo foi criado por um robo
-->